// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:wingle/common/constants/env_constants.dart';
import 'package:wingle/common/utils/env_util.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: EnvUtil.get(FirebaseEnvFile.androidApiKey),
    appId: EnvUtil.get(FirebaseEnvFile.androidAppId),
    messagingSenderId: EnvUtil.get(FirebaseEnvFile.messagingSenderId),
    projectId: EnvUtil.get(FirebaseEnvFile.projectId),
    storageBucket: EnvUtil.get(FirebaseEnvFile.storageBucket),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvUtil.get(FirebaseEnvFile.iosApiKey),
    appId: EnvUtil.get(FirebaseEnvFile.iosAppId),
    messagingSenderId: EnvUtil.get(FirebaseEnvFile.messagingSenderId),
    projectId: EnvUtil.get(FirebaseEnvFile.projectId),
    storageBucket: EnvUtil.get(FirebaseEnvFile.storageBucket),
    iosBundleId: EnvUtil.get(FirebaseEnvFile.iosBundleId),
  );
}
